### ISSUE TITLE
Initialize Precipitation values with array of zeros.

### ISSUE THREAD

**Issue by saeranv** [ladybug-tools/uwg#102]
We're recently had two Ladybug users that have run into issues with the UWG while using customized EPW files (i.e morphed future projection data) that lacked a column for precipitation. I encouraged both to simply add zero values for precipitation in the original file to get the simulation to work. 

As we've discussed previously, the current implementation of the UWG doesn't use precipitation data due to the difficulty in validating latent heat impact, the poor quality precipitation data from weather sensors, and the marginal impact it has on UHI. 

Despite this, the weather object in UWG is still reading in the precipitation values from the EPW file, which is causing issues for custom EPW files. I propose we simply initialize the precipitation array with zeros to avoid this error. I don't think we should get rid of it completely, since there's a lot of (commented) code in the current UWG that refers to the precipitation array, that provides useful context regarding UWG's handling of precipitation and latent heat.

@hansukyang, do you see any problems with this?

S

**Comment by hansukyang** [comment]
That should be fine - I can't think of any reason this would cause problem but let me know if it does.

**Comment by saeranv** [comment]
Done! And it seems to pass all the tests. Thanks @hansukyang
