### ISSUE TITLE
Roof vegetation

### ISSUE THREAD

**Issue by simonmarti1992** [ladybug-tools/uwg#105]
Hi everybody,

I'm currently running sensitiviy analysis on the uwg code. I'm a bit surprised that the roof vegetation seems to have no influence on the results. I have found in the code  :
self.BEM[k].roof.vegCoverage = self.vegRoof in the uwg.py
But I'm not sure this input is used. In the SurFlux function in the element.py, the following balance :
vegLat = self.vegCoverage*parameter.grassFLat*(1.-parameter.vegAlbedo)*self.solRec
shows that vegCoverage is used in the heat balance for the horizontal surface. 

My question : does the parameter "vegCoverage" is also used for roof coverage ?

Best regards,
Simon MARTINEZ

**Comment by saeranv** [comment]
@simonmarti1992 

Yes, the vegCoverage you see being used to calculate the sensible and latent vegetation heat there (vegLat and vegSens) are both a function of the roof vegCoverage defined in uwg.py. 

The section you're referring to updates the roof sensible and latent heat with regard to vegetation, 
https://github.com/ladybug-tools/uwg/blob/5f6c715a7b6cde31a4578f88faf0d12d81c49121/uwg/element.py#L125-L128

This section updates the roof/vegetation long-wave radiation:
https://github.com/ladybug-tools/uwg/blob/5f6c715a7b6cde31a4578f88faf0d12d81c49121/uwg/urbflux.py#L29-L32

And then the resulting heat flux is used in the building to urban bounday layer (UBL) heat balance (this version of the UWG assumes the urban canyon volume is bounded to building height, so all the heat from the roof rises to the UBL).  
https://github.com/ladybug-tools/uwg/blob/5f6c715a7b6cde31a4578f88faf0d12d81c49121/uwg/element.py#L141-L145

If you review these code snippets you can get an idea of what parameters you can manipulate to change the impact of roof vegetation (vegetable albedo, start/end dates of vegetation season, latent fraction of grass etc).

**Comment by saeranv** [comment]
@simonmarti1992 

It's been a long time, but I wanted to post an update that you were correct, the code wasn't accounting for the roof vegetation fraction. I've been doing some unrelated revisions to the UWG, and stumbled upon the reason why you weren't seeing any change in the UHI with changes to the roof vegetation.

Basically, the original code had set all the roofs as a vertical constructions (rather then horizontal): https://github.com/hansukyang/UWG_Matlab/blob/master/readDOE.m#L233-L259. The element surface flux calculation for the roof constructions therefore weren't accounting for the element vegCoverage. This has been fixed, and will be released in the next version of the UWG.

**Comment by saeranv** [comment]
Closed, as this is now solved with latest UWG PR.
