### ISSUE TITLE
Possible error in uwg.py

### ISSUE THREAD

**Issue by jmrk87** [ladybug-tools/uwg#248]
Hi,
I found this in uwg.py.
        # fraction of vegetation (tree & grass) coverage on unbuilt surface
        road_veg_coverage = self.vegcover / (1 - self.blddensity)
        road_grass_coverage = self.treecover / (1 - self.blddensity)
        road_tree_coverage = self.grasscover / (1 - self.blddensity)
It would seem that self.grasscover and self.treecover are inverted.

Thanks,
G.

**Comment by saeranv** [comment]
@jmrk87 

Yeah I agree, that looks like a bug, and may actually explain some weird behaviour I've seen with tree/grass fractions before.

**Comment by chriswmackey** [comment]
Thanks @jmrk87 and @saeranv . I'm fixing this one now.
