### ISSUE TITLE
Change UWG_Matlab's road buffering method to match our revised UWG_Python method?

### ISSUE THREAD

**Issue by saeranv** [ladybug-tools/uwg#25]
@hansukyang, @chriswmackey 

UWG_Python uses the ".m" input method for reading inputs from UWG_Matlab, but uses its ".xml" method's for road slicing/buffering (as we discussed in issue #16). Therefore UWG_Matlab and UWG_Python currently have two different ways of modifying road thicknesses, for the  ".m" file input. Should we change UWG_Matlab's code to be consistent with UWG_Python's?  

I've already gone ahead and modified the code for my personal UWG_Matlab repo clone I've been using for testing. I realized when I started translating the surface flux calculations for the roads, that I needed to change the UWG_Matlab code so that I could compare the outputs of the two versions.

I basically moved [the .xml method of road buffering to the .m read input section](https://github.com/saeranv/UWG_Matlab_Sandbox/commit/f6946b6be067a66b8e5bcc37ec94416ffb007182#diff-9632f200381a440ff7b0f67023895b3bR287). And then [modifed the procMat method to take the road objects created from the .m files](https://github.com/saeranv/UWG_Matlab_Sandbox/commit/f6946b6be067a66b8e5bcc37ec94416ffb007182#diff-9632f200381a440ff7b0f67023895b3bR1020). 

What do you guys think? Is it important to try and keep both versions consistent, and make these sames changes in the original UWG_Matlab repo?

**Comment by hansukyang** [comment]
Hi Saeren,

Good point, I think both should be kept consistent if they are both being
used. I've cc'ed Jiachen Mao, Les' grad student who should be the current
maintainer of UWG Matlab. I think he may be maintaining a separate version
than the UWG_Matlab repository under my account, so perhaps he (or Les) can
chime in as well.

Joseph

**Comment by saeranv** [comment]
Closing this as looks like UWG v 5 has departed enough from v 4 that it's not worth doing.
