### ISSUE TITLE
buildings area

### ISSUE THREAD

**Issue by simonmarti1992** [ladybug-tools/uwg#254]
Hi everybody,
I'm not sur I 100% understand the building model ou uwg. I saw in Joseph H. Yang master thesis that each type of buildign get its own area. So, does "charLength" of the simulation should be change depending on this building are ? 
Best regards,
Simon

**Comment by t-vasas** [comment]
@simonmarti1992, the characteristic length is the dimension of a square that encompasses the whole neighborhood, so it depends on the maximum length of the entire analysis area.  We reccomend keeping the analysis area to have a `charLength` of 1000m (as set in the defaults), which is based on a study[1] that found a 500m radius analysis area achieved the most accurate output. This roughly corresponds to a study by Oke[2] that found a 500 m radius is the extent at which temperature/humidity sensors at 1.5m heights will be influenced by the surrounding urban site, although this varies based on density. Beyond that 500m, the temperature/humidity influence decays and thus defines the recommended constraint on the UWG neighborhood analysis area.  

[1] https://dspace.mit.edu/handle/1721.1/82284
[2] Oke, T.R., "Initial guidance to obtain representative meteorological observations at urban sites" 2006.

**Comment by saeranv** [comment]
@simonmarti1992, the characteristic length is the dimension of a square that encompasses the whole neighborhood, so it depends on the maximum length of the entire analysis area. We reccomend keeping the analysis area to have a charLength of 1000m (as set in the defaults), which is based on a study[1] that found a 500m radius analysis area achieved the most accurate output. This roughly corresponds to a study by Oke[2] that found a 500 m radius is the extent at which temperature/humidity sensors at 1.5m heights will be influenced by the surrounding urban site, although this varies based on density. Beyond that 500m, the temperature/humidity influence decays and thus defines the recommended constraint on the UWG neighborhood analysis area.

[1] https://dspace.mit.edu/handle/1721.1/82284
[2] Oke, T.R., "Initial guidance to obtain representative meteorological observations at urban sites" 2006.
