### ISSUE TITLE
Example UWG file in resources is out of date

### ISSUE THREAD

**Issue by danieldjewell** [ladybug-tools/uwg#255]
Issue is still unresolved from #139 

The 6ff8e44ef0a35217d9f9bfc213c4dcbb926fdeff commit looks like it changed the format for the UWG file, specifically for how the ```bld``` parameter is read.

Trouble is, the example file in resources/ was never updated and it's still using the old format.

**Comment by saeranv** [comment]
@danieldjewell 

You're going to have to clarify this a bit more. For one thing, issue #139 never indicated any errors with UWG, it was purely a user error, and so all the changes I made were mainly cosmetic (changing error messages, the README etc). 

It'll be better to just share the code you're trying to run and what error message you're getting.

**Comment by danieldjewell** [comment]
Try running: https://github.com/ladybug-tools/uwg/blob/6ddbdc88a64034f748e98c0f157e434323399c7e/resources/initialize_singapore.uwg

It will fail because the format for bld is old...
https://github.com/ladybug-tools/uwg/blob/6ddbdc88a64034f748e98c0f157e434323399c7e/resources/initialize_singapore.uwg#L58-L68

**Comment by saeranv** [comment]
@danieldjewell 

Good catch! I did miss updating this file. Fixing it now.

**Comment by saeranv** [comment]
The updated file has be merged, thanks again @danieldjewell.

**Comment by danieldjewell** [comment]
> The updated file has be merged, thanks again @danieldjewell.

No worries! Thank you! (Side note/suggestion -- maybe add some notes in the readme to look at some of the test files - they're more than just tests, they're also examples :) )
