### ISSUE TITLE
UWG Processor 

### ISSUE THREAD

**Issue by aleksandraradecka1** [ladybug-tools/uwg#268]
Hello, 

I am using UWG tool in QGIS (UMEP plugin) and I encountered a problem at the final stage of running the algorithm - while calculating .epw files for each grid based on .uwg files and one .epw file from the meteorological station (https://energyplus.net/weather):

if the .uwg filenames start with "p" e.g. they are: "prep_1", "prep_2_, "prep_3" etc., they algorithm produces two .epw files for each grid element - first with the same name "prep_1", "prep_2", "prep_3" and second "rep_1_UWG", "rep_2_UWG", "rep_3_UWG". Later the algorithm expects to obtain one file "prep_1_UWG", "prep_2_UWG", "prep_3_UWG" what of course results in an error.

Fredrik Lindberg, the author of QGIS implementation, and I checked that filenames starting with "p" does not work, but "t" are OK. 

I would be grateful for checking this behaviour. 
Aleksandra

**Comment by chriswmackey** [comment]
Hi @aleksandraradecka1 ,

Sorry for such a late response here. I was able to recreate the issue and I included a fix here:
https://github.com/ladybug-tools/uwg/pull/282/commits/7368f58ff65ddf6fa74963b1f9e9cbd91372cd8e

It looks like any file that started with an e, p, or w would have been affected. Thanks for reporting!
