### ISSUE TITLE
UWG EPW double `\n` per line

### ISSUE THREAD

**Issue by AntoineDao** [ladybug-tools/uwg#80]
I was experimenting with Dragonfly/UWG and was parsing EPW files using pandas (standard `pd.read_csv()`) and noticed it would work fine on normal EPWs but the morphed EPWs resulting from Dragonfly/UWG would break reader.

After some investigating I noticed that lines in UWG produced EPWs are escapes like so `\n\n` as opposed to `\n` in normal EPWs.

This is a cosmetic issue when looking through the EPW file but if we are aiming to then parse and compare with standard EPWs after running simulations this could be problematic.

**Comment by saeranv** [comment]
Agree it's something that needs to be fixed if that's the case. 

This is the write epw method in uwg, which I ported over from the matlab code:

https://github.com/ladybug-tools/uwg/blob/0f8cb80555daf86cca4c5f0c703e5f23465ba711/uwg/uwg.py#L861-L898

At first glance can't see why it's adding an extra line. I wonder if it's the carriage return '/r', which seems redundant to me. I'll need to find some time to investigate further.

**Comment by chriswmackey** [comment]
Good point, @AntoineDao .  Bruno probably put the carriage return in there because he was originally working exclusively on Windows systems and wanted to mimic the Windows "Enter".

The correct, cross-platform way to write the line break is what the original EPW files are using (just a single \n).  So I think we should change it to be a single \n.

See here for a reference:
https://stackoverflow.com/questions/10059142/reading-r-carriage-return-vs-n-newline-from-console-with-getc/10059171

**Comment by chriswmackey** [comment]
Also, @AntoineDao , why are you using pandas to parse the EPW?  Is there something missing from the EPW object in the Ladybug core that you feel the need to use Pandas for?

**Comment by saeranv** [comment]
> The correct, cross-platform way to write the line break is what the original EPW files are using (just a single \n). So I think we should change it to be a single \n.

Thanks, you're right, I just checked and that solved it. Made the change and merged the new code with - #81.

**Comment by AntoineDao** [comment]
Thanks for the quick resolution on this @saeranv. Just as a heads up, you might have noticed that your changes were not deployed to PyPi. This is because you did not use the semantic versioning syntax in your commit. We can make future commits with this which will deploy the most up to date so lets not worry about fixing this one just yet. If you're wanting to know more about semantic-release and how it works I'd recommend checking [this link](https://blog.greenkeeper.io/introduction-to-semantic-release-33f73b117c8).

**Comment by saeranv** [comment]
Ah I see! I'll read the link, and make sure to follow the semantic versioning syntax from here on out.

**Comment by saeranv** [comment]
@AntoineDao 

I got a whole bunch of changes to the code I want to commit, but I'm a little confused about how to do it with proper semantic versioning. 

Are we using this commitizen tool that the link you referenced? Or do we just have to modify our commit messages?
