### ISSUE TITLE
Error in line 735

### ISSUE THREAD

**Issue by maririvo** [ladybug-tools/uwg#97]
Has someone had error in line 735? We cannot model UWG 4 because of an error in Line 735. We have been told to close all office programms and to modify line 756, but it did not work. The error does not say anything apart from that. 
Thank you!

**Comment by saeranv** [comment]
@maririvo We'll need more information to help. Can you copy and paste the full error statement you're getting from the program?

Also are you running UWG through grasshopper, or in directly through python?

S

**Comment by saeranv** [comment]
@maririvo 

Just to clarify, this is the git repo for UWG 5. UWG version 4.1, and lower was written in Matlab which you can access here https://github.com/hansukyang/UWG_Matlab or here https://github.com/aiko-nakano/Urban-Weather-Generator.  They are not being as actively maintained as UWG 5.

**Comment by maririvo** [comment]
That is right. I will try to start using UWG 5. 
Thank you.

Marina
