### ISSUE TITLE
Runtime Error Argument out of range

### ISSUE THREAD

**Issue by LuciaC91** [ladybug-tools/uwg#98]
Hi, I am having some issues when installing Dragon Fly in Grasshopper. It says Runtime Error, ArgumentOutOfRangeException.I attach an image
Has anyone had the same problem? Thank you

![image](https://user-images.githubusercontent.com/47979726/53649565-2858b400-3c21-11e9-814a-cfab10b6d1fe.png)

**Comment by saeranv** [comment]
Apologies that I didn't catch this sooner.  I assume this is likely fixed at this point so am going to close out this issue.  If this is still an issue please open an issue in the appropriate dragonfly-legacy or dragonfly repo.
