### ISSUE TITLE
No changes in simulation results when improving system efficiency or increasing thermal insulation

### ISSUE THREAD

**Issue by elelac** [ladybug-tools/uwg#99]
Hi everyone! I'm a Master student from Italy and I started to use the UWG Python version to assess the UHI effect on local case studies for my Master thesis. I'm new to programming and to Python, so I hope that my question won't seem too banal. 
My thesis goal is to assess the UHI effect on local buildings that I precisely characterized from the geometrical, architectural and usage point of view (basically, beside filling in the initialize file, I also changed the default values of DOE Reference Buildings folders to make them more realistic and similar to the buildings of my city) . Beside the current situation, I wanted to test the implications on UHI effect of different retrofit scenarios (condensing boilers, heat pumps, an increase of thermal insulation, etc), but I'm facing a problem. The results that I'm getting for the different scenarios are the same for the "base" scenario. 
At first, I thought it was my fault, maybe putting the wrong values, but I did many simulations and the situation doesn't change. So far, I tested 5 situations:

    Scenario 1 : changing from gas boilers (Heating efficiency=0.6) to condensing boilers (Heating efficiency=0.8) --> no changes
    Scenario 2: changing from gas boilers (Heating efficiency=0.6) to biomass boilers (Heating efficiency=0.62) --> no changes
    Scenario 3: changing from gas boilers (Heating efficiency=0.6) to heat pumps (Heating efficiency=3.18) --> no changes
    Scenario 4: changing from gas boilers (Heating efficiency=0.6) to heat pumps (Heating efficiency=3.18)  + adding external thermal insulation to walls (Resistance values about 2.7 compared to previous resistance about 0.90) --> no changes
    Scenario 5: changing from gas boilers (Heating efficiency=0.6) to heat pumps (Heating efficiency=3.18)  + adding external thermal insulation to walls (Resistance values about 2.7) + considering PV integrated into the roof (Albedo roof = 0.3) --> slight changes

To be sure that I called the right file among all building typologies' .csv files, last time I tried something "drastic": I put the values of my building in each building typology and each column of climate zones, so it's like there is only one building typology with its characteristics in the program. However, the results were once again the same. 
Given this, I started to question the relevance of thermal insulation and system efficiency on final results or the way the program itself accounts for them in the outdoor air temperature calculation, also because I've learned from literature that building output to canyon influences the UHI effect. Enhancing system efficiency (for example using heat pumps) should have slightly reduced canyon temperatures since heat pumps extract heat from the canyon instead of releasing it. Has anyone ever faced something like this? Or made thoughts about the relevance of system efficiency and thermal insulation on the phenomenon/how UWG deals with it? 
Thanks in advance for the availability. I'm here to learn about the program and the UHI phenomenon itself, so every answer is welcomed. 

Eleonora

**Comment by chriswmackey** [comment]
Hi @elelac ,

@saeranv might be better at answering these questions that I but I would not expect the boiler or heat pumps to have a significant effect on UHI unless the `heat_rejection_to_canyon` is also high.  And, even in that case, I wouldn't expect the UHI to change much unless you drop the COP to something pretty low.

You might want to check out this thesis that involves a sensitivity study of different variables to the urban heat island effect:
https://dspace.mit.edu/handle/1721.1/99251

**Comment by chriswmackey** [comment]
Also, remember for the case of heat pumps that any COP above 1 means that the majority of the heat rejected into the urban environment comes from the interior of buildings (not the electricity going into the pump).

**Comment by saeranv** [comment]
@elelac, 

Sorry for the late response here.  I agree with @chriswmackey on checking out Nakano's thesis, and the limited effect of boiler/heat pump efficiency in UHI. 

A couple of other points:

> Enhancing system efficiency (for example using heat pumps) should have slightly reduced canyon temperatures since heat pumps extract heat from the canyon instead of releasing it. 

The extraction of heat from the canyon for heat pumps isn't modeled by the UWG (wouldn't this be fairly trivial anyway? The heat from cool air isn't that high...). The primary impact of your heat pump would be the reduced heat exhausted to the canyon, as a function of it's efficiency. You can see this here: 
https://github.com/ladybug-tools/uwg/blob/fb71f656b3cb69e7ccf1d851dff862e14fa210fc/uwg/building.py#L276-L285

From there the waste heat calculation is performed :
https://github.com/ladybug-tools/uwg/blob/fb71f656b3cb69e7ccf1d851dff862e14fa210fc/uwg/building.py#L337-L340

And finally, here's where the waste heat is factored into the canyon sensible heat/air: 
https://github.com/ladybug-tools/uwg/blob/4beddbc093ce572e2da5cbb3ea5ab2b04f3b2f8c/uwg/UCMDef.py#L220-L238

The `h_mix` parameter there refers to the `heat_rejection_to_canyon` Chris mentioned above.

The UCMDef class is where the heat transfer from building to the canyon is budgeted. So if you're interested in investigating this further, I'd start there. Specifically this section accounting for waste heat: https://github.com/ladybug-tools/uwg/blob/master/uwg/UCMDef.py#L220, and this section, further upstream, which takes an area-weighted heat components from building assembly surface and ambient temperatures. You can trace back the impact of your heating equipment efficiencies, and insulation impact, respectively, with these two sections.

Finally, the derived dry bulb, dew point, and wind speed from the UWG is rounded to one significant digit, which is going to obscure any subtle changes generated from your sensitivity analysis. You can change this in the UWG object by modifying the uwg.epw_precision parameter to a couple of more digits.


S

**Comment by elelac** [comment]
Many thanks for your replies! I agree that enhanced efficiencies should lead to smaller heat exhausted into the canyon (sensWaste). It's exactly examining its definition as heatConsump - Qheat that we came up with the idea that modelling heat pumps was possible: if the heating efficiency is higher than 1, then heatConsump is smaller than Qheat turning the heating related sensWaste value from positive to negative. 
With regard to program's sensitivity to heating efficiency, in one of the numerous attempts we set the heating efficiency value to 0.9 in the definition of BEMCalc function (line 128 of building.py file) and surprisingly we observed the first differences in results, so in my opinion there could be some problems in the way the programs reads the new building characteristics that I added for Italian buildings, replacing the ones contained in the .csv files. In addition, we didn't understand how does the \uwg\refdata\readDOE.pkl file work: it seems like that the code reload building characteristics from this pre-saved file that is never reloaded after my parameter changes and to be honest, I'm not able to fix on my own. Could you please give me some more information about it? 
Sorry for instisting on this issue, but I think that making the program even more customizable, allowing users to provide their local buildings' characteristics could be of use for everyone, especially for those aiming at using UWG outside the U.S. Thanks in advance for the availability.

Eleonora

**Comment by saeranv** [comment]
@elelac 

> In addition, we didn't understand how does the \uwg\refdata\readDOE.pkl file work: it seems like that the code reload building characteristics from this pre-saved file that is never reloaded after my parameter changes and to be honest, I'm not able to fix on my own. Could you please give me some more information about it?

Oh, now I see where the mistake is occurring! Yes you're correct, the readDOE.pkl file needs to be updated for the changes in your csv to be accounted for in the UWG. There's a comment in the readDOE.py that explains how: 
 https://github.com/ladybug-tools/uwg/blob/fb71f656b3cb69e7ccf1d851dff862e14fa210fc/uwg/readDOE.py#L376-L383

The easiest way to do this is go into your terminal, navigate to the UWG main directory (uwg/ not uwg/uwg/) and type:  `python -m uwg.readDOE --serialize`, anytime you make a change to your csv. 

Reading the same text file everytime we want to run the UWG would be very inefficient. So the readDOE.py file converts the text file into python objects representing the DOE prototype buildings, and then serializes them into the readDOE.pkl. Pickles are the fastest way to store and access high-level data structures like objects in python. 

This should solve your problem.

S

**Comment by saeranv** [comment]
>  I agree that enhanced efficiencies should lead to smaller heat exhausted into the canyon (sensWaste). It's exactly examining its definition as heatConsump - Qheat that we came up with the idea that modelling heat pumps was possible: if the heating efficiency is higher than 1, then heatConsump is smaller than Qheat turning the heating related sensWaste value from positive to negative.

Interesting! You're right, this should work.

**Comment by saeranv** [comment]
I'm going to close this issue, as presumably creating a new pkl was the solution to this problem. And for future uses, users can now use the uwg-schema to change the building properties.
